// ── Top 400 US Cities + Remote ──────────────────────────────────────────────

export const US_CITIES: string[] = [
  'Remote',
  'New York, NY',
  'Los Angeles, CA',
  'Chicago, IL',
  'Houston, TX',
  'Phoenix, AZ',
  'Philadelphia, PA',
  'San Antonio, TX',
  'San Diego, CA',
  'Dallas, TX',
  'San Jose, CA',
  'Austin, TX',
  'Jacksonville, FL',
  'Fort Worth, TX',
  'Columbus, OH',
  'Charlotte, NC',
  'Indianapolis, IN',
  'San Francisco, CA',
  'Seattle, WA',
  'Denver, CO',
  'Washington, DC',
  'Nashville, TN',
  'Oklahoma City, OK',
  'El Paso, TX',
  'Boston, MA',
  'Portland, OR',
  'Las Vegas, NV',
  'Memphis, TN',
  'Louisville, KY',
  'Baltimore, MD',
  'Milwaukee, WI',
  'Albuquerque, NM',
  'Tucson, AZ',
  'Fresno, CA',
  'Sacramento, CA',
  'Mesa, AZ',
  'Kansas City, MO',
  'Atlanta, GA',
  'Omaha, NE',
  'Colorado Springs, CO',
  'Raleigh, NC',
  'Long Beach, CA',
  'Virginia Beach, VA',
  'Miami, FL',
  'Oakland, CA',
  'Minneapolis, MN',
  'Tampa, FL',
  'Tulsa, OK',
  'Arlington, TX',
  'New Orleans, LA',
  'Wichita, KS',
  'Cleveland, OH',
  'Bakersfield, CA',
  'Aurora, CO',
  'Anaheim, CA',
  'Honolulu, HI',
  'Santa Ana, CA',
  'Riverside, CA',
  'Corpus Christi, TX',
  'Lexington, KY',
  'Stockton, CA',
  'Pittsburgh, PA',
  'Saint Paul, MN',
  'Anchorage, AK',
  'Cincinnati, OH',
  'Henderson, NV',
  'Greensboro, NC',
  'Plano, TX',
  'Newark, NJ',
  'Lincoln, NE',
  'Orlando, FL',
  'Irvine, CA',
  'Toledo, OH',
  'Jersey City, NJ',
  'Chula Vista, CA',
  'Durham, NC',
  'Laredo, TX',
  'Madison, WI',
  'Chandler, AZ',
  'Buffalo, NY',
  'Lubbock, TX',
  'Scottsdale, AZ',
  'Reno, NV',
  'Glendale, AZ',
  'Gilbert, AZ',
  'Winston-Salem, NC',
  'North Las Vegas, NV',
  'Norfolk, VA',
  'Chesapeake, VA',
  'Garland, TX',
  'Irving, TX',
  'Hialeah, FL',
  'Fremont, CA',
  'Boise, ID',
  'Richmond, VA',
  'Baton Rouge, LA',
  'Spokane, WA',
  'Des Moines, IA',
  'Tacoma, WA',
  'San Bernardino, CA',
  'Modesto, CA',
  'Fontana, CA',
  'Moreno Valley, CA',
  'Santa Clarita, CA',
  'Fayetteville, NC',
  'Birmingham, AL',
  'Oxnard, CA',
  'Rochester, NY',
  'Port St. Lucie, FL',
  'Grand Rapids, MI',
  'Huntsville, AL',
  'Salt Lake City, UT',
  'Frisco, TX',
  'Yonkers, NY',
  'Amarillo, TX',
  'Glendale, CA',
  'Huntington Beach, CA',
  'McKinney, TX',
  'Montgomery, AL',
  'Augusta, GA',
  'Aurora, IL',
  'Akron, OH',
  'Little Rock, AR',
  'Tempe, AZ',
  'Overland Park, KS',
  'Grand Prairie, TX',
  'Tallahassee, FL',
  'Cape Coral, FL',
  'Mobile, AL',
  'Knoxville, TN',
  'Shreveport, LA',
  'Worcester, MA',
  'Ontario, CA',
  'Vancouver, WA',
  'Sioux Falls, SD',
  'Chattanooga, TN',
  'Brownsville, TX',
  'Fort Lauderdale, FL',
  'Providence, RI',
  'Newport News, VA',
  'Rancho Cucamonga, CA',
  'Santa Rosa, CA',
  'Peoria, AZ',
  'Oceanside, CA',
  'Elk Grove, CA',
  'Salem, OR',
  'Pembroke Pines, FL',
  'Eugene, OR',
  'Garden Grove, CA',
  'Cary, NC',
  'Corona, CA',
  'Springfield, MO',
  'Fort Collins, CO',
  'Jackson, MS',
  'Alexandria, VA',
  'Hayward, CA',
  'Lancaster, CA',
  'Lakewood, CO',
  'Clarksville, TN',
  'Palmdale, CA',
  'Salinas, CA',
  'Springfield, IL',
  'Hollywood, FL',
  'Pasadena, TX',
  'Sunnyvale, CA',
  'Macon, GA',
  'Kansas City, KS',
  'Pomona, CA',
  'Escondido, CA',
  'Savannah, GA',
  'Bridgeport, CT',
  'Joliet, IL',
  'Naperville, IL',
  'Bellevue, WA',
  'Rockford, IL',
  'Paterson, NJ',
  'Killeen, TX',
  'Torrance, CA',
  'Dayton, OH',
  'McAllen, TX',
  'Columbia, SC',
  'Charleston, SC',
  'Murfreesboro, TN',
  'Midland, TX',
  'Surprise, AZ',
  'Denton, TX',
  'Roseville, CA',
  'Thornton, CO',
  'Miramar, FL',
  'Waco, TX',
  'Olathe, KS',
  'Carrollton, TX',
  'West Valley City, UT',
  'Sterling Heights, MI',
  'New Haven, CT',
  'Thousand Oaks, CA',
  'Cedar Rapids, IA',
  'Visalia, CA',
  'Ann Arbor, MI',
  'Provo, UT',
  // ── Additional suburbs ──
  'Alpharetta, GA',
  'Allen, TX',
  'Apex, NC',
  'Avon, OH',
  'Ballwin, MO',
  'Beaverton, OR',
  'Bethesda, MD',
  'Boca Raton, FL',
  'Bolingbrook, IL',
  'Bothell, WA',
  'Brentwood, TN',
  'Broken Arrow, OK',
  'Brookfield, WI',
  'Brooklyn Park, MN',
  'Burbank, CA',
  'Burlington, MA',
  'Canton, MI',
  'Castle Rock, CO',
  'Centennial, CO',
  'Chesterfield, MO',
  'Colleyville, TX',
  'Conroe, TX',
  'Coral Springs, FL',
  'Cupertino, CA',
  'Davie, FL',
  'Decatur, GA',
  'Draper, UT',
  'Dublin, OH',
  'Duluth, GA',
  'Edmond, OK',
  'Eagan, MN',
  'Eden Prairie, MN',
  'Encinitas, CA',
  'Fishers, IN',
  'Flower Mound, TX',
  'Folsom, CA',
  'Franklin, TN',
  'Germantown, MD',
  'Grapevine, TX',
  'Hoboken, NJ',
  'Johns Creek, GA',
  'Keller, TX',
  'Kennesaw, GA',
  'Kirkland, WA',
  'Lake Oswego, OR',
  'Lakeville, MN',
  'Leander, TX',
  'Lee\'s Summit, MO',
  'Lehi, UT',
  'Lewisville, TX',
  'Lisle, IL',
  'Littleton, CO',
  'Lone Tree, CO',
  'Maple Grove, MN',
  'Marietta, GA',
  'Mason, OH',
  'Milpitas, CA',
  'Minnetonka, MN',
  'Mountain View, CA',
  'Noblesville, IN',
  'Northbrook, IL',
  'Novi, MI',
  'Owings Mills, MD',
  'Palo Alto, CA',
  'Parker, CO',
  'Pearland, TX',
  'Pflugerville, TX',
  'Plymouth, MN',
  'Redmond, WA',
  'Redwood City, CA',
  'Reston, VA',
  'Rocklin, CA',
  'Rogers, AR',
  'Roswell, GA',
  'Round Rock, TX',
  'San Clemente, CA',
  'San Mateo, CA',
  'San Ramon, CA',
  'Sandy Springs, GA',
  'Santa Clara, CA',
  'Schaumburg, IL',
  'Simi Valley, CA',
  'South Jordan, UT',
  'Southlake, TX',
  'Sugar Land, TX',
  'Temecula, CA',
  'Troy, MI',
  'Tustin, CA',
  'Walnut Creek, CA',
  'West Des Moines, IA',
  'West Hartford, CT',
  'Westlake, OH',
  'Westerville, OH',
  'Woodbury, MN',
  'Woodlands, TX',
  'Yorba Linda, CA',
  // ── State capitals ──
  'Albany, NY',
  'Annapolis, MD',
  'Augusta, ME',
  'Bismarck, ND',
  'Carson City, NV',
  'Cheyenne, WY',
  'Concord, NH',
  'Dover, DE',
  'Frankfort, KY',
  'Harrisburg, PA',
  'Hartford, CT',
  'Helena, MT',
  'Jefferson City, MO',
  'Juneau, AK',
  'Lansing, MI',
  'Montpelier, VT',
  'Olympia, WA',
  'Pierre, SD',
  'Santa Fe, NM',
  'Topeka, KS',
  'Trenton, NJ',
  // ── Mid-size cities ──
  'Abilene, TX',
  'Appleton, WI',
  'Asheville, NC',
  'Athens, GA',
  'Beaumont, TX',
  'Bellingham, WA',
  'Bend, OR',
  'Billings, MT',
  'Bloomington, IN',
  'Bloomington, IL',
  'Boulder, CO',
  'Bowling Green, KY',
  'Bryan, TX',
  'Burlington, VT',
  'Champaign, IL',
  'College Station, TX',
  'Columbia, MO',
  'Corvallis, OR',
  'Davenport, IA',
  'Duluth, MN',
  'East Lansing, MI',
  'Eau Claire, WI',
  'Erie, PA',
  'Evansville, IN',
  'Fargo, ND',
  'Flagstaff, AZ',
  'Gainesville, FL',
  'Green Bay, WI',
  'Greenville, SC',
  'Hagerstown, MD',
  'Ithaca, NY',
  'Kalamazoo, MI',
  'Key West, FL',
  'La Crosse, WI',
  'Lafayette, LA',
  'Lake Charles, LA',
  'Las Cruces, NM',
  'Lawrence, KS',
  'Lynchburg, VA',
  'Mankato, MN',
  'Medford, OR',
  'Missoula, MT',
  'Myrtle Beach, SC',
  'New Braunfels, TX',
  'Norman, OK',
  'Ocala, FL',
  'Ogden, UT',
  'Panama City, FL',
  'Pensacola, FL',
  'Peoria, IL',
  'Rapid City, SD',
  'Redding, CA',
  'Rochester, MN',
  'San Angelo, TX',
  'San Marcos, TX',
  'Santa Barbara, CA',
  'Santa Cruz, CA',
  'Sarasota, FL',
  'Scranton, PA',
  'Spartanburg, SC',
  'Springfield, MA',
  'Springfield, OH',
  'State College, PA',
  'St. George, UT',
  'St. Cloud, MN',
  'Stillwater, OK',
  'Syracuse, NY',
  'Terre Haute, IN',
  'Tyler, TX',
  'Utica, NY',
  'Valdosta, GA',
  'Vero Beach, FL',
  'Wausau, WI',
  'Wilmington, NC',
  'Wilmington, DE',
  'Yakima, WA',
  'York, PA',
  'Yuma, AZ',
]

// ── Common Job Titles ───────────────────────────────────────────────────────

export const JOB_TITLES: string[] = [
  'Software Engineer',
  'Senior Software Engineer',
  'Full Stack Developer',
  'Frontend Developer',
  'Backend Developer',
  'Mobile Developer',
  'DevOps Engineer',
  'Data Scientist',
  'Data Analyst',
  'Data Engineer',
  'Machine Learning Engineer',
  'Product Manager',
  'Project Manager',
  'Program Manager',
  'Engineering Manager',
  'Technical Lead',
  'Solutions Architect',
  'Cloud Engineer',
  'QA Engineer',
  'UX Designer',
  'UI Designer',
  'UX Researcher',
  'Graphic Designer',
  'Marketing Manager',
  'Digital Marketing Specialist',
  'Content Strategist',
  'SEO Specialist',
  'Sales Representative',
  'Account Manager',
  'Account Executive',
  'Business Analyst',
  'Business Development Manager',
  'Financial Analyst',
  'Accountant',
  'Human Resources Manager',
  'HR Coordinator',
  'Recruiter',
  'Operations Manager',
  'Supply Chain Manager',
  'Customer Success Manager',
  'Technical Writer',
  'Cybersecurity Analyst',
  'Network Engineer',
  'Systems Administrator',
  'Database Administrator',
  'Registered Nurse',
  'Physician Assistant',
  'Pharmacist',
  'Physical Therapist',
  'Teacher',
]

// ── Skills by Job Title ─────────────────────────────────────────────────────

export const SKILLS_BY_JOB: Record<string, string[]> = {
  'software engineer': [
    'JavaScript', 'TypeScript', 'Python', 'Java', 'C++', 'Git',
    'REST APIs', 'SQL', 'Docker', 'AWS', 'Agile/Scrum', 'CI/CD',
  ],
  'senior software engineer': [
    'System Design', 'Code Review', 'Mentoring', 'TypeScript', 'Python',
    'Microservices', 'AWS', 'Docker', 'Kubernetes', 'CI/CD', 'SQL', 'NoSQL',
  ],
  'full stack developer': [
    'React', 'Node.js', 'TypeScript', 'PostgreSQL', 'MongoDB', 'REST APIs',
    'GraphQL', 'HTML/CSS', 'Docker', 'AWS', 'Git', 'Agile',
  ],
  'frontend developer': [
    'React', 'TypeScript', 'HTML5', 'CSS3', 'Tailwind CSS', 'Next.js',
    'Redux', 'Responsive Design', 'Accessibility (WCAG)', 'Jest', 'Figma', 'Git',
  ],
  'backend developer': [
    'Node.js', 'Python', 'Java', 'PostgreSQL', 'Redis', 'REST APIs',
    'GraphQL', 'Docker', 'AWS', 'Microservices', 'CI/CD', 'Linux',
  ],
  'mobile developer': [
    'React Native', 'Swift', 'Kotlin', 'Flutter', 'iOS', 'Android',
    'TypeScript', 'REST APIs', 'Firebase', 'App Store Deployment', 'Git', 'UI/UX',
  ],
  'devops engineer': [
    'AWS', 'Docker', 'Kubernetes', 'Terraform', 'CI/CD', 'Linux',
    'Jenkins', 'GitHub Actions', 'Monitoring', 'Ansible', 'Python', 'Bash',
  ],
  'data scientist': [
    'Python', 'R', 'SQL', 'Machine Learning', 'TensorFlow', 'PyTorch',
    'Pandas', 'NumPy', 'Data Visualization', 'Statistical Analysis', 'Jupyter', 'Scikit-learn',
  ],
  'data analyst': [
    'SQL', 'Python', 'Excel', 'Tableau', 'Power BI', 'Data Visualization',
    'Statistical Analysis', 'R', 'Google Analytics', 'ETL', 'A/B Testing', 'Reporting',
  ],
  'data engineer': [
    'Python', 'SQL', 'Spark', 'Airflow', 'AWS', 'Kafka',
    'ETL Pipelines', 'Data Modeling', 'Redshift', 'Snowflake', 'dbt', 'Docker',
  ],
  'machine learning engineer': [
    'Python', 'TensorFlow', 'PyTorch', 'Scikit-learn', 'NLP', 'Computer Vision',
    'Deep Learning', 'MLOps', 'AWS SageMaker', 'Docker', 'SQL', 'Feature Engineering',
  ],
  'product manager': [
    'Product Strategy', 'User Research', 'Agile/Scrum', 'Roadmapping', 'A/B Testing',
    'Jira', 'Data Analysis', 'Stakeholder Management', 'PRDs', 'SQL', 'Figma', 'OKRs',
  ],
  'project manager': [
    'Project Planning', 'Agile/Scrum', 'Waterfall', 'Risk Management', 'Jira',
    'Stakeholder Communication', 'Budget Management', 'MS Project', 'Gantt Charts', 'PMP',
  ],
  'engineering manager': [
    'Team Leadership', 'Hiring', 'Mentoring', 'Agile/Scrum', 'Technical Strategy',
    'Performance Reviews', 'Cross-functional Collaboration', 'Architecture Design', 'OKRs', 'Budget Management',
  ],
  'technical lead': [
    'Architecture Design', 'Code Review', 'Mentoring', 'System Design', 'Agile/Scrum',
    'Technical Decision-Making', 'TypeScript', 'Python', 'AWS', 'CI/CD', 'Microservices',
  ],
  'solutions architect': [
    'AWS', 'Azure', 'GCP', 'System Design', 'Microservices', 'Enterprise Architecture',
    'Cloud Migration', 'Security', 'API Design', 'DevOps', 'Kubernetes', 'Terraform',
  ],
  'cloud engineer': [
    'AWS', 'Azure', 'GCP', 'Terraform', 'Docker', 'Kubernetes',
    'CI/CD', 'Linux', 'Networking', 'Security', 'Python', 'CloudFormation',
  ],
  'qa engineer': [
    'Test Automation', 'Selenium', 'Cypress', 'Jest', 'Manual Testing', 'API Testing',
    'Performance Testing', 'CI/CD', 'Jira', 'Test Planning', 'Python', 'SQL',
  ],
  'ux designer': [
    'Figma', 'User Research', 'Wireframing', 'Prototyping', 'Usability Testing',
    'Design Systems', 'Information Architecture', 'Interaction Design', 'Accessibility', 'Adobe XD',
  ],
  'ui designer': [
    'Figma', 'Adobe Creative Suite', 'Typography', 'Color Theory', 'Design Systems',
    'Responsive Design', 'Prototyping', 'HTML/CSS', 'Iconography', 'Motion Design',
  ],
  'graphic designer': [
    'Adobe Photoshop', 'Adobe Illustrator', 'InDesign', 'Figma', 'Typography',
    'Brand Identity', 'Print Design', 'Layout Design', 'Color Theory', 'Photography',
  ],
  'marketing manager': [
    'Digital Marketing', 'Content Strategy', 'SEO/SEM', 'Google Analytics', 'Social Media',
    'Email Marketing', 'Brand Management', 'Campaign Management', 'HubSpot', 'Budget Management',
  ],
  'digital marketing specialist': [
    'Google Ads', 'Facebook Ads', 'SEO', 'SEM', 'Google Analytics',
    'Email Marketing', 'Content Marketing', 'Social Media', 'A/B Testing', 'HubSpot',
  ],
  'sales representative': [
    'Salesforce', 'CRM', 'Cold Calling', 'Lead Generation', 'Negotiation',
    'Pipeline Management', 'B2B Sales', 'Presentations', 'Account Management', 'Closing',
  ],
  'account manager': [
    'Client Relations', 'Account Growth', 'CRM', 'Salesforce', 'Negotiation',
    'Retention Strategy', 'Cross-selling', 'Presentations', 'Contract Management', 'Upselling',
  ],
  'business analyst': [
    'Requirements Gathering', 'SQL', 'Excel', 'Data Analysis', 'Process Mapping',
    'Jira', 'Stakeholder Management', 'User Stories', 'Wireframing', 'Tableau',
  ],
  'financial analyst': [
    'Financial Modeling', 'Excel', 'SQL', 'Bloomberg', 'Forecasting',
    'Variance Analysis', 'Budgeting', 'Power BI', 'VBA', 'Financial Reporting',
  ],
  'accountant': [
    'GAAP', 'QuickBooks', 'Excel', 'Financial Reporting', 'Tax Preparation',
    'Accounts Payable/Receivable', 'Reconciliation', 'Auditing', 'SAP', 'Budgeting',
  ],
  'human resources manager': [
    'Recruitment', 'Employee Relations', 'HRIS', 'Compliance', 'Benefits Administration',
    'Performance Management', 'Training & Development', 'Policy Development', 'ADP', 'Conflict Resolution',
  ],
  'recruiter': [
    'Sourcing', 'LinkedIn Recruiter', 'ATS', 'Interviewing', 'Employer Branding',
    'Candidate Assessment', 'Negotiation', 'Pipeline Management', 'Boolean Search', 'Onboarding',
  ],
  'operations manager': [
    'Process Improvement', 'Supply Chain', 'Budget Management', 'Team Leadership',
    'Lean/Six Sigma', 'Vendor Management', 'KPI Tracking', 'Logistics', 'ERP Systems', 'Quality Control',
  ],
  'customer success manager': [
    'Client Onboarding', 'Retention Strategy', 'CRM', 'Account Management', 'Churn Reduction',
    'Product Adoption', 'Customer Health Scoring', 'Upselling', 'Training', 'Stakeholder Communication',
  ],
  'technical writer': [
    'API Documentation', 'Markdown', 'DITA', 'Git', 'Developer Docs',
    'Content Management', 'Information Architecture', 'Style Guides', 'Confluence', 'HTML/CSS',
  ],
  'cybersecurity analyst': [
    'SIEM', 'Incident Response', 'Vulnerability Assessment', 'Penetration Testing', 'Firewalls',
    'Network Security', 'Compliance (SOC 2, ISO 27001)', 'Python', 'Threat Modeling', 'NIST',
  ],
  'network engineer': [
    'Cisco', 'TCP/IP', 'Firewalls', 'VPN', 'DNS', 'DHCP',
    'Network Monitoring', 'Routing/Switching', 'CCNA/CCNP', 'Load Balancing', 'Wireshark', 'SD-WAN',
  ],
  'systems administrator': [
    'Linux', 'Windows Server', 'Active Directory', 'VMware', 'Bash',
    'PowerShell', 'Monitoring', 'Backup & Recovery', 'DNS', 'DHCP', 'Networking',
  ],
  'database administrator': [
    'PostgreSQL', 'MySQL', 'SQL Server', 'Oracle', 'MongoDB',
    'Performance Tuning', 'Backup & Recovery', 'Replication', 'Data Modeling', 'Security', 'ETL',
  ],
  'registered nurse': [
    'Patient Assessment', 'IV Therapy', 'Electronic Health Records (EHR)', 'Medication Administration',
    'Critical Thinking', 'Patient Education', 'Wound Care', 'BLS/ACLS', 'Team Collaboration', 'Charting',
  ],
  'teacher': [
    'Curriculum Development', 'Lesson Planning', 'Classroom Management', 'Differentiated Instruction',
    'Student Assessment', 'Educational Technology', 'Communication', 'IEP Development', 'Google Classroom', 'Parent Engagement',
  ],
}

// ── Description Bullets by Job Title ────────────────────────────────────────

export const DESCRIPTION_BULLETS_BY_JOB: Record<string, string[]> = {
  'software engineer': [
    'Designed and implemented scalable microservices handling 10K+ requests per second',
    'Reduced API response times by 40% through query optimization and caching strategies',
    'Led migration from monolithic architecture to event-driven microservices',
    'Wrote comprehensive unit and integration tests achieving 90%+ code coverage',
    'Collaborated with product and design teams to deliver features on schedule',
    'Mentored junior developers through code reviews and pair programming sessions',
    'Implemented CI/CD pipelines reducing deployment time from hours to minutes',
    'Resolved critical production incidents with minimal downtime through systematic debugging',
  ],
  'senior software engineer': [
    'Architected and led implementation of a new platform serving 1M+ daily users',
    'Reduced infrastructure costs by 35% through performance optimization and right-sizing',
    'Established coding standards and best practices adopted across the engineering org',
    'Led technical design reviews and drove architectural decisions for key systems',
    'Mentored team of 5 engineers, with 2 promoted within 12 months',
    'Drove adoption of TypeScript across 15+ services, reducing production bugs by 25%',
    'Designed fault-tolerant distributed systems with 99.99% uptime SLA',
    'Partnered with product to define technical roadmap and prioritize tech debt reduction',
  ],
  'full stack developer': [
    'Built responsive web applications using React and Node.js serving 50K+ users',
    'Developed RESTful APIs and integrated third-party services for payment processing',
    'Implemented real-time features using WebSockets for live collaboration',
    'Optimized database queries reducing page load times by 60%',
    'Created reusable component library used across 5 internal applications',
    'Implemented authentication and authorization using OAuth 2.0 and JWT',
  ],
  'frontend developer': [
    'Built responsive, accessible UI components following WCAG 2.1 AA standards',
    'Improved Core Web Vitals scores by 50% through code splitting and lazy loading',
    'Developed design system with 40+ reusable components adopted across 3 product teams',
    'Migrated legacy jQuery codebase to React, improving developer productivity by 30%',
    'Implemented state management using Redux, reducing unnecessary re-renders by 45%',
    'Collaborated with UX designers to translate Figma mockups into pixel-perfect interfaces',
  ],
  'backend developer': [
    'Designed and maintained RESTful APIs serving 5M+ requests daily',
    'Implemented database sharding strategy supporting 10x data growth',
    'Built real-time data processing pipelines handling 100K+ events per minute',
    'Developed microservices using Node.js and Python with Docker containerization',
    'Implemented rate limiting and authentication middleware for API security',
    'Optimized PostgreSQL queries reducing average response time from 500ms to 50ms',
  ],
  'devops engineer': [
    'Automated infrastructure provisioning using Terraform, reducing setup time by 80%',
    'Implemented Kubernetes-based container orchestration for 50+ microservices',
    'Built CI/CD pipelines enabling 100+ deployments per week with zero downtime',
    'Reduced cloud infrastructure costs by 40% through monitoring and right-sizing',
    'Implemented centralized logging and monitoring using ELK stack and Prometheus',
    'Designed disaster recovery strategies achieving RPO of 1 hour and RTO of 4 hours',
  ],
  'data scientist': [
    'Developed ML models improving prediction accuracy by 25% over baseline',
    'Built recommendation engine increasing user engagement by 30%',
    'Created automated data pipelines processing 5TB+ of data daily',
    'Conducted A/B tests resulting in 15% improvement in conversion rates',
    'Presented data-driven insights to C-level stakeholders informing product strategy',
    'Developed NLP models for sentiment analysis achieving 92% accuracy',
  ],
  'data analyst': [
    'Created interactive dashboards in Tableau used by 50+ stakeholders',
    'Automated weekly reporting processes saving 10+ hours per week',
    'Conducted cohort analysis identifying key factors in customer retention',
    'Designed and analyzed A/B tests driving 20% improvement in conversion',
    'Built SQL-based ETL processes for data warehouse population',
    'Presented quarterly business reviews with actionable recommendations to leadership',
  ],
  'product manager': [
    'Led product strategy for a platform generating $5M+ in annual revenue',
    'Defined and prioritized product roadmap based on user research and data analysis',
    'Launched 3 major features resulting in 25% increase in user engagement',
    'Conducted user interviews and usability studies to validate product hypotheses',
    'Collaborated with engineering, design, and marketing teams on product launches',
    'Managed product backlog and sprint planning for a team of 8 engineers',
  ],
  'project manager': [
    'Managed cross-functional teams of 10-15 members across 5 concurrent projects',
    'Delivered projects on time and within budget, averaging 5% under budget',
    'Implemented Agile methodology resulting in 30% faster delivery cycles',
    'Created and maintained project plans, risk registers, and status reports',
    'Facilitated stakeholder communication and managed expectations across org levels',
    'Led vendor negotiations saving $200K annually in software licensing costs',
  ],
  'ux designer': [
    'Conducted user research with 100+ participants informing product design decisions',
    'Designed end-to-end user flows improving task completion rates by 35%',
    'Created and maintained design system with 60+ components and documentation',
    'Led usability testing sessions identifying and resolving 20+ UX issues',
    'Collaborated with engineering to ensure design fidelity in implementation',
    'Reduced customer support tickets by 40% through intuitive onboarding redesign',
  ],
  'marketing manager': [
    'Managed $500K annual marketing budget across digital and traditional channels',
    'Increased organic traffic by 150% through SEO and content strategy',
    'Launched email campaigns achieving 35% open rate and 8% click-through rate',
    'Developed brand guidelines adopted across all marketing materials',
    'Led rebranding initiative resulting in 20% increase in brand awareness',
    'Managed team of 4 marketing specialists and 3 external agency partners',
  ],
  'sales representative': [
    'Exceeded quarterly sales targets by 120% consistently for 8 consecutive quarters',
    'Generated $2M+ in new business revenue through strategic prospecting',
    'Built and maintained a pipeline of 150+ qualified leads',
    'Closed enterprise deals with average contract value of $100K+',
    'Developed and delivered product demonstrations to C-level executives',
    'Collaborated with marketing on lead generation campaigns increasing MQLs by 40%',
  ],
  'business analyst': [
    'Gathered and documented business requirements for 10+ major initiatives',
    'Created process flow diagrams and data models for system implementations',
    'Conducted gap analysis identifying $500K in potential cost savings',
    'Facilitated workshops with stakeholders to define project scope and priorities',
    'Developed user stories and acceptance criteria for Agile development teams',
    'Built financial models and dashboards for executive decision-making',
  ],
  'financial analyst': [
    'Built financial models for M&A transactions totaling $50M+',
    'Prepared monthly variance analysis reports for senior leadership',
    'Developed 3-year financial forecasts with 95% accuracy',
    'Automated reporting processes using VBA macros saving 15 hours per month',
    'Conducted industry and competitive analysis informing investment decisions',
    'Managed budgeting process for department with $10M annual budget',
  ],
  'human resources manager': [
    'Led recruiting efforts resulting in 50+ hires across engineering and sales',
    'Reduced employee turnover by 20% through engagement initiatives',
    'Designed and implemented performance review process for 200+ employees',
    'Managed benefits administration and open enrollment for 300+ employees',
    'Developed DEI programs increasing workforce diversity by 15%',
    'Created onboarding program reducing time-to-productivity by 30%',
  ],
  'operations manager': [
    'Streamlined operations processes reducing costs by 25% annually',
    'Managed team of 30+ across warehouse, logistics, and customer service',
    'Implemented Lean Six Sigma methodology improving efficiency by 35%',
    'Negotiated vendor contracts saving $300K annually',
    'Developed KPI dashboards for real-time operational performance tracking',
    'Led ISO 9001 certification process ensuring quality compliance',
  ],
  'customer success manager': [
    'Managed portfolio of 50+ enterprise accounts with $3M+ ARR',
    'Achieved 95% customer retention rate through proactive engagement',
    'Increased account expansion revenue by 30% through strategic upselling',
    'Developed customer health scoring framework adopted across the CS team',
    'Led quarterly business reviews for top-tier clients',
    'Reduced time-to-value by 40% through improved onboarding process',
  ],
  'teacher': [
    'Developed and delivered curriculum for 120+ students across 4 class sections',
    'Improved standardized test scores by 15% through differentiated instruction',
    'Implemented technology-enhanced learning using Google Classroom and educational apps',
    'Mentored 5 student teachers through practicum placements',
    'Led after-school tutoring program serving 30+ at-risk students',
    'Organized parent engagement events increasing participation by 40%',
  ],
  'registered nurse': [
    'Provided direct patient care for 6-8 patients per shift in acute care setting',
    'Administered medications and treatments following physician orders and protocols',
    'Collaborated with interdisciplinary healthcare team to develop care plans',
    'Mentored and trained 5 new graduate nurses during orientation period',
    'Maintained accurate patient documentation in electronic health records',
    'Participated in quality improvement initiatives reducing infection rates by 15%',
  ],
}

// ── Summary Templates by Job Title ──────────────────────────────────────────

export const GENERIC_SUMMARY_TEMPLATES: string[] = [
  'Dedicated professional with [X] years of experience delivering high-quality results in fast-paced environments. Known for strong analytical thinking, clear communication, and a collaborative approach to solving complex challenges across cross-functional teams.',
  'Motivated and detail-oriented professional with a proven track record of exceeding goals and driving measurable outcomes. Skilled in project management, stakeholder communication, and adapting quickly to evolving priorities and technologies.',
  'Results-driven professional with [X] years of experience combining technical expertise with business acumen. Passionate about continuous learning, process optimization, and mentoring team members to achieve collective success.',
  'Versatile professional with a strong foundation in problem-solving and strategic planning. Experienced in managing multiple projects simultaneously while maintaining attention to detail and delivering on tight deadlines.',
  'Accomplished professional with expertise in leading initiatives that improve efficiency, reduce costs, and enhance customer satisfaction. Adept at translating complex requirements into actionable plans that drive organizational growth.',
]

export const SUMMARY_TEMPLATES_BY_JOB: Record<string, string[]> = {
  'software engineer': [
    'Software engineer with [X] years of experience building scalable web applications and distributed systems. Proficient in JavaScript, TypeScript, and Python with a strong foundation in cloud architecture, API design, and agile development methodologies.',
    'Results-driven software engineer specializing in full-stack development with expertise across the entire software lifecycle. Passionate about writing clean, maintainable code and delivering high-impact features that improve user experience and drive business value.',
    'Detail-oriented software engineer with experience in agile environments building production systems used by thousands of users daily. Skilled in designing RESTful APIs, optimizing database performance, implementing CI/CD pipelines, and contributing to architectural decisions that shape product direction.',
    'Collaborative software engineer with [X] years of hands-on experience in modern web technologies and cloud platforms. Proven ability to quickly ramp up on new codebases, debug complex production issues, and deliver reliable software solutions that meet both technical and business requirements.',
    'Software engineer with a passion for building elegant solutions to complex technical problems. Experienced in microservices architecture, test-driven development, and performance optimization with a track record of reducing system latency and improving reliability across production environments.',
    'Innovative software engineer skilled in designing and implementing features that serve millions of users. Strong background in data structures, algorithms, and system design with hands-on experience in AWS, Docker, and modern JavaScript frameworks.',
  ],
  'senior software engineer': [
    'Senior software engineer with [X]+ years of experience leading technical initiatives and mentoring development teams. Expert in system design, microservices architecture, and cloud-native technologies with a proven ability to translate business requirements into scalable, maintainable software systems.',
    'Accomplished senior engineer with a track record of delivering complex systems at scale across multiple product domains. Strong communicator who bridges technical and business stakeholders to drive product success while maintaining high engineering standards and team velocity.',
    'Technical leader with deep expertise in distributed systems and platform engineering. Passionate about building high-performing teams, establishing engineering best practices, and architecting solutions that balance innovation with reliability and long-term maintainability.',
    'Senior software engineer with extensive experience in leading end-to-end product development from concept to production. Skilled in mentoring junior and mid-level engineers, conducting design reviews, and driving adoption of modern development practices across engineering organizations.',
    'Experienced senior engineer with a strong background in performance optimization, infrastructure modernization, and technical debt reduction. Known for delivering pragmatic solutions that balance short-term business needs with long-term architectural vision and scalability.',
    'Senior software engineer specializing in building resilient, high-availability systems that process millions of transactions daily. Expert in event-driven architecture, observability, and leading cross-team initiatives that improve developer experience and deployment confidence.',
  ],
  'full stack developer': [
    'Full stack developer with expertise in React, Node.js, and cloud technologies. Experienced in building end-to-end web applications from database design to responsive UI implementation, with a focus on performance, accessibility, and maintainable code architecture.',
    'Versatile full stack developer passionate about creating intuitive user experiences backed by robust server-side architecture. Strong background in the JavaScript/TypeScript ecosystem with hands-on experience in PostgreSQL, MongoDB, and cloud deployment platforms.',
    'Full stack developer with [X] years of experience delivering production-grade applications across diverse industries. Proficient in modern frontend frameworks, RESTful and GraphQL APIs, and DevOps practices that streamline development workflows and reduce time to deployment.',
    'Creative full stack developer with a strong eye for UI/UX and deep backend expertise. Experienced in building real-time features, integrating third-party services, and optimizing application performance from the database layer through to the client-side rendering pipeline.',
    'Proactive full stack developer skilled in rapidly prototyping and iterating on product ideas. Experienced in startup and enterprise environments, building everything from MVPs to production systems handling thousands of concurrent users with modern web technologies.',
  ],
  'frontend developer': [
    'Frontend developer specializing in React and TypeScript with a keen eye for design and user experience. Experienced in building accessible, performant web applications and scalable design systems that serve as the foundation for consistent product experiences.',
    'Creative frontend developer with [X] years of experience crafting responsive, user-centered interfaces. Passionate about web performance, accessibility, and modern CSS techniques with a strong track record of improving Core Web Vitals and user engagement metrics.',
    'Frontend developer with deep expertise in component architecture, state management, and modern build tooling. Skilled in translating complex Figma designs into pixel-perfect, production-ready interfaces while maintaining clean, testable code across large-scale applications.',
    'Detail-oriented frontend developer experienced in building design systems used by multiple product teams. Proficient in React, Next.js, and Tailwind CSS with strong opinions on accessibility, semantic HTML, and progressive enhancement strategies.',
    'Frontend engineer with a passion for creating delightful user experiences that balance visual polish with performance. Experienced in animation, micro-interactions, and responsive design across desktop, tablet, and mobile breakpoints.',
  ],
  'backend developer': [
    'Backend developer experienced in designing high-throughput APIs and data processing systems that handle millions of requests per day. Proficient in Node.js, Python, and SQL/NoSQL databases with strong DevOps skills and infrastructure automation experience.',
    'Skilled backend engineer focused on building reliable, scalable services in production environments. Deep expertise in database optimization, API design, cloud infrastructure, and implementing security best practices across the application stack.',
    'Backend developer with [X] years of experience building microservices architectures that support rapid feature development and independent deployment. Proficient in message queues, caching strategies, and observability tools that ensure system reliability at scale.',
    'Performance-focused backend engineer experienced in designing systems that process large volumes of data with low latency. Skilled in database sharding, connection pooling, and horizontal scaling strategies across AWS and containerized environments.',
    'Backend developer with strong expertise in API design, authentication systems, and data pipeline architecture. Experienced in building event-driven systems, implementing rate limiting and access control, and maintaining services with 99.9%+ uptime.',
  ],
  'mobile developer': [
    'Mobile developer with [X] years of experience building native and cross-platform applications for iOS and Android. Proficient in React Native, Swift, and Kotlin with a strong understanding of mobile design patterns, offline-first architecture, and app store deployment processes.',
    'Versatile mobile developer skilled in building performant, user-friendly apps that serve thousands of daily active users. Experienced in integrating REST APIs, push notifications, analytics, and in-app purchase flows across both major mobile platforms.',
    'Mobile engineer with deep expertise in React Native and native platform APIs. Passionate about smooth animations, responsive layouts, and accessible mobile experiences with a track record of publishing apps that achieve high user ratings and strong retention.',
    'Creative mobile developer experienced in building consumer-facing applications from concept to App Store/Play Store launch. Skilled in mobile CI/CD, automated testing, and performance profiling to deliver polished, reliable apps on tight timelines.',
  ],
  'data scientist': [
    'Data scientist with [X] years of experience applying machine learning and statistical analysis to solve business problems at scale. Proficient in Python, SQL, and data visualization tools with expertise in building models that drive measurable business outcomes and inform strategic decision-making.',
    'Analytical data scientist with expertise in predictive modeling, NLP, and A/B testing. Passionate about turning complex data into actionable insights that drive business growth, with hands-on experience deploying models to production and monitoring their performance over time.',
    'Data scientist skilled in the full ML lifecycle from exploratory data analysis through feature engineering, model training, and production deployment. Experienced in deep learning frameworks, cloud computing platforms, and communicating technical findings to non-technical stakeholders.',
    'Innovative data scientist with a strong statistical foundation and practical engineering skills. Experienced in building recommendation systems, forecasting models, and automated data pipelines that generate insights across marketing, product, and operations functions.',
    'Research-oriented data scientist with [X] years of experience in computer vision, natural language processing, and time-series analysis. Published researcher with expertise in TensorFlow, PyTorch, and modern MLOps practices for scalable model training and deployment.',
  ],
  'data analyst': [
    'Data analyst with strong SQL and visualization skills, experienced in turning raw data into actionable business insights that inform executive decision-making. Proficient in Tableau, Python, and statistical analysis with a track record of building self-service analytics platforms.',
    'Detail-oriented data analyst with [X] years of experience in business intelligence and reporting across marketing, finance, and product domains. Skilled in building dashboards, automating data pipelines, and conducting cohort and funnel analyses that drive strategic planning.',
    'Data analyst with a passion for finding stories in data and communicating them clearly to diverse audiences. Experienced in SQL, Python, and modern BI tools with expertise in A/B testing, experimental design, and statistical significance assessment.',
    'Business-focused data analyst skilled in translating stakeholder questions into analytical frameworks and delivering insights that drive measurable improvements. Proficient in building ETL processes, creating executive dashboards, and mentoring team members on data literacy.',
  ],
  'data engineer': [
    'Data engineer with [X] years of experience designing and maintaining scalable data infrastructure that powers analytics and machine learning across the organization. Proficient in Python, SQL, Spark, and cloud data platforms including Snowflake, Redshift, and BigQuery.',
    'Experienced data engineer skilled in building reliable ETL/ELT pipelines, data warehouses, and streaming architectures that process terabytes of data daily. Strong background in Airflow, Kafka, and infrastructure-as-code tools with a focus on data quality and observability.',
    'Data engineer passionate about building self-service data platforms that democratize access to insights. Experienced in dbt, data modeling, and implementing data governance frameworks that ensure consistency, reliability, and compliance across analytical workflows.',
    'Cloud-native data engineer with expertise in designing lakehouse architectures and real-time data processing systems. Skilled in optimizing query performance, reducing infrastructure costs, and mentoring analysts on best practices for working with large-scale datasets.',
  ],
  'machine learning engineer': [
    'Machine learning engineer with [X] years of experience bridging the gap between research and production ML systems. Proficient in Python, TensorFlow, and PyTorch with expertise in building scalable training pipelines, model serving infrastructure, and automated retraining workflows.',
    'MLOps-focused engineer experienced in deploying and monitoring machine learning models at scale across diverse domains including NLP, computer vision, and recommendation systems. Skilled in feature stores, experiment tracking, and A/B testing frameworks that ensure model reliability.',
    'Machine learning engineer with strong software engineering fundamentals and deep understanding of statistical learning theory. Experienced in building end-to-end ML pipelines from data ingestion through model deployment, with a focus on latency optimization and cost efficiency.',
  ],
  'product manager': [
    'Product manager with [X] years of experience launching successful digital products that serve millions of users. Skilled in user research, data analysis, and cross-functional collaboration to drive product-market fit while balancing technical constraints with business opportunities.',
    'Strategic product manager with a technical background, experienced in defining product vision and roadmap across multiple product lines. Passionate about building products that solve real user problems at scale, backed by quantitative metrics and qualitative user insights.',
    'Customer-obsessed product manager with expertise in discovery, experimentation, and go-to-market strategy. Proven track record of launching features that increased engagement, reduced churn, and grew revenue through data-informed decision-making and iterative development.',
    'Product manager with experience in both B2B and B2C environments, skilled in managing complex stakeholder relationships while maintaining focus on user needs. Proficient in SQL, analytics tools, and agile methodologies with a strong bias toward shipping and learning.',
    'Growth-oriented product manager with [X] years of experience driving activation, retention, and monetization improvements through systematic experimentation. Experienced in funnel analysis, pricing strategy, and building cross-functional alignment around ambitious product goals.',
  ],
  'project manager': [
    'PMP-certified project manager with [X] years of experience delivering complex projects on time and within budget across technology, marketing, and operations domains. Skilled in Agile and Waterfall methodologies with strong stakeholder management and risk mitigation capabilities.',
    'Results-oriented project manager experienced in leading cross-functional teams of 10-20 members across multiple concurrent workstreams. Strong track record of process improvement, vendor management, and building repeatable project frameworks that scale.',
    'Agile project manager with deep experience in scrum mastering, sprint planning, and retrospective facilitation. Passionate about removing blockers, improving team velocity, and creating transparent communication channels between technical teams and business stakeholders.',
    'Strategic project manager skilled in managing enterprise-scale programs with budgets exceeding $1M. Experienced in change management, resource allocation, and using data-driven approaches to track project health and predict potential delivery risks.',
  ],
  'engineering manager': [
    'Engineering manager with [X] years of experience building and scaling high-performing engineering teams. Skilled in hiring, mentoring, and career development with a proven track record of delivering complex technical initiatives while maintaining team health and engineering excellence.',
    'People-first engineering manager experienced in growing teams from 5 to 30+ engineers across multiple product areas. Expert in establishing engineering culture, technical strategy, and cross-functional collaboration that drives both individual growth and organizational impact.',
    'Technical engineering leader with hands-on experience in system design and a passion for developing talent. Skilled in setting OKRs, managing technical debt, and creating environments where engineers do their best work through clear expectations and psychological safety.',
  ],
  'ux designer': [
    'UX designer with [X] years of experience creating user-centered digital experiences across web and mobile platforms. Skilled in user research, wireframing, prototyping, and design system development with a strong portfolio of products that improved usability and business metrics.',
    'Human-centered UX designer passionate about accessibility and inclusive design. Experienced in conducting qualitative and quantitative research, usability testing, and translating insights into intuitive interfaces that reduce friction and increase user satisfaction.',
    'Strategic UX designer with expertise in information architecture, interaction design, and design thinking facilitation. Experienced in leading design sprints, defining design principles, and collaborating closely with engineering teams to ensure design intent is preserved in implementation.',
    'UX designer with a strong visual design background and deep empathy for users. Skilled in building design systems from scratch, conducting competitive analyses, and using data to validate design decisions across the full product lifecycle.',
    'Research-driven UX designer with [X] years of experience across SaaS, e-commerce, and healthcare products. Expert in mapping user journeys, identifying pain points, and designing solutions that balance user needs with business goals and technical constraints.',
  ],
  'ui designer': [
    'UI designer with [X] years of experience creating polished, visually compelling interfaces for web and mobile products. Expert in typography, color theory, and responsive design with a strong portfolio of design systems and component libraries.',
    'Creative UI designer skilled in translating brand identity into cohesive digital experiences. Proficient in Figma, motion design, and accessibility standards with a passion for pixel-perfect implementation and seamless collaboration with frontend engineers.',
    'UI designer with a keen eye for detail and deep understanding of design trends and platform-specific conventions. Experienced in building scalable design systems, creating interactive prototypes, and mentoring junior designers on visual design best practices.',
  ],
  'marketing manager': [
    'Marketing manager with [X] years of experience driving growth through integrated digital and traditional marketing strategies. Skilled in SEO, content strategy, and campaign management with proven ROI results and experience managing marketing budgets exceeding $500K annually.',
    'Strategic marketing leader experienced in brand development, demand generation, and team management across B2B and B2C contexts. Data-driven approach to optimizing marketing spend and improving conversion rates through systematic testing and audience segmentation.',
    'Growth-focused marketing manager with expertise in performance marketing, marketing automation, and cross-channel attribution. Experienced in building and leading marketing teams, managing agency relationships, and developing go-to-market strategies for product launches.',
    'Digital marketing manager skilled in building scalable content engines, email nurture campaigns, and paid acquisition strategies that deliver measurable pipeline growth. Proficient in HubSpot, Google Analytics, and modern marketing technology stacks.',
  ],
  'digital marketing specialist': [
    'Digital marketing specialist with [X] years of experience managing paid and organic campaigns across search, social, and display channels. Proficient in Google Ads, Facebook Ads, and analytics platforms with a track record of reducing CAC while scaling acquisition volume.',
    'Data-driven digital marketing specialist skilled in A/B testing, conversion rate optimization, and marketing automation. Experienced in building landing pages, email sequences, and retargeting campaigns that move prospects through the funnel efficiently.',
    'Creative digital marketer with expertise in content marketing, SEO, and social media strategy. Skilled in developing multi-channel campaigns that build brand awareness, drive engagement, and generate qualified leads for sales teams.',
  ],
  'sales representative': [
    'Top-performing sales professional with [X] years of experience exceeding quotas in B2B SaaS environments. Skilled in consultative selling, pipeline management, and building lasting client relationships that drive renewals and expansion revenue.',
    'Results-driven sales representative with a track record of generating $X+ in annual revenue through strategic prospecting and relationship building. Expert in negotiation, closing enterprise deals, and collaborating with marketing on demand generation initiatives.',
    'Ambitious sales professional with expertise in outbound prospecting, demo delivery, and contract negotiation. Experienced in full-cycle sales from lead qualification through close, with a strong focus on understanding customer pain points and delivering tailored solutions.',
    'Enterprise sales representative with [X] years of experience managing complex deal cycles involving multiple decision-makers. Skilled in value-based selling, ROI analysis, and building executive-level relationships that accelerate deal velocity.',
  ],
  'account manager': [
    'Strategic account manager with [X] years of experience growing and retaining enterprise client portfolios. Skilled in building executive relationships, identifying upsell opportunities, and delivering business reviews that demonstrate ROI and strengthen partnerships.',
    'Relationship-driven account manager with a track record of maintaining 95%+ client retention rates. Experienced in cross-selling, contract renewals, and acting as the primary liaison between clients and internal product, engineering, and support teams.',
    'Proactive account manager skilled in developing account growth strategies that consistently exceed expansion revenue targets. Experienced in managing portfolios of $5M+ ARR with a focus on customer satisfaction, advocacy, and long-term value creation.',
  ],
  'business analyst': [
    'Business analyst with [X] years of experience bridging business needs and technical solutions across finance, healthcare, and technology sectors. Skilled in requirements gathering, process modeling, and stakeholder communication with strong analytical and documentation capabilities.',
    'Detail-oriented business analyst experienced in Agile environments and skilled at working closely with product managers and engineering teams. Proficient in SQL, data analysis, and creating comprehensive documentation including user stories, acceptance criteria, and process flows.',
    'Business analyst with expertise in process improvement, systems analysis, and change management. Experienced in conducting gap analyses, facilitating workshops, and translating complex business requirements into clear, actionable specifications for development teams.',
    'Analytical business professional with [X] years of experience using data to inform strategic decisions and improve operational efficiency. Skilled in building financial models, conducting market research, and presenting findings to executive leadership.',
  ],
  'financial analyst': [
    'Financial analyst with [X] years of experience in financial modeling, forecasting, and variance analysis across corporate finance and investment banking. Proficient in Excel, SQL, and business intelligence tools with a keen eye for detail and accuracy.',
    'CFA-track financial analyst with expertise in M&A analysis, valuation, and financial reporting. Strong quantitative skills with experience in building DCF models, sensitivity analyses, and board-level presentations that inform strategic investment decisions.',
    'Financial analyst skilled in budgeting, scenario planning, and cross-functional financial partnership. Experienced in automating reporting processes, improving forecast accuracy, and providing data-driven recommendations to senior leadership on resource allocation and growth initiatives.',
  ],
  'human resources manager': [
    'HR professional with [X] years of experience in talent acquisition, employee relations, and organizational development. Skilled in building inclusive workplace cultures that drive retention, engagement, and high performance across diverse teams.',
    'Strategic HR manager experienced in scaling teams from 50 to 200+ employees while maintaining culture and operational efficiency. Expert in benefits administration, compliance, performance management systems, and developing career frameworks that support employee growth.',
    'People-focused HR leader with expertise in recruiting strategy, employer branding, and learning and development programs. Experienced in implementing HRIS platforms, designing compensation structures, and leading DEI initiatives that create measurable workplace improvements.',
    'Human resources manager with [X] years of experience supporting organizations through periods of rapid growth and organizational change. Skilled in change management, workforce planning, and building HR processes that scale without losing the human touch.',
  ],
  'recruiter': [
    'Technical recruiter with [X] years of experience sourcing and hiring top engineering, product, and design talent in competitive markets. Expert in building diverse candidate pipelines, managing stakeholder expectations, and creating exceptional candidate experiences throughout the hiring process.',
    'Full-cycle recruiter skilled in Boolean sourcing, employer branding, and interview process design. Experienced in hiring across multiple functions and levels, from individual contributors to director-level roles, with a consistent track record of reducing time-to-fill.',
    'Relationship-driven recruiter with expertise in building talent communities and long-term candidate relationships. Skilled in market mapping, compensation benchmarking, and partnering with hiring managers to develop job descriptions and interview rubrics that attract exceptional candidates.',
  ],
  'operations manager': [
    'Operations manager with [X] years of experience optimizing processes and reducing costs across manufacturing, logistics, and service operations. Lean Six Sigma certified with expertise in supply chain management, vendor relations, and continuous improvement methodologies.',
    'Results-driven operations leader experienced in managing teams of 30+ across multiple locations while maintaining quality standards and operational efficiency. Strong track record of implementing process improvements that reduce waste, lower costs, and improve customer satisfaction.',
    'Strategic operations manager skilled in ERP implementation, inventory management, and workforce optimization. Experienced in building scalable operational frameworks that support rapid business growth while maintaining compliance and quality control standards.',
  ],
  'customer success manager': [
    'Customer success manager with [X] years of experience managing enterprise accounts and driving product adoption across SaaS platforms. Skilled in building strategic relationships, reducing churn, and identifying expansion opportunities that grow account revenue.',
    'Proactive customer success professional with a track record of maintaining 95%+ retention rates across portfolios of 50+ accounts. Experienced in building scalable onboarding processes, customer health scoring frameworks, and executive business review programs.',
    'Strategic CSM with expertise in customer journey mapping, value realization, and cross-functional advocacy. Experienced in partnering with product teams to relay customer feedback, influence roadmap priorities, and ensure customers achieve their desired outcomes.',
    'Customer success manager with [X] years of experience in B2B SaaS, skilled in managing complex enterprise relationships involving multiple stakeholders. Proven ability to drive adoption metrics, lead renewal negotiations, and mentor junior team members.',
  ],
  'technical writer': [
    'Technical writer with [X] years of experience creating developer documentation, API references, and user guides for complex software products. Proficient in Markdown, DITA, and docs-as-code workflows with a strong ability to make technical concepts accessible to diverse audiences.',
    'Versatile technical writer experienced in collaborating with engineering and product teams to document features, APIs, and architectural decisions. Skilled in information architecture, content strategy, and building documentation sites that scale with product growth.',
    'Technical communicator with expertise in API documentation, SDK guides, and developer onboarding materials. Experienced in managing documentation repositories, implementing style guides, and using analytics to improve content effectiveness and discoverability.',
  ],
  'cybersecurity analyst': [
    'Cybersecurity analyst with [X] years of experience in threat detection, incident response, and vulnerability management across enterprise environments. Proficient in SIEM tools, network security, and compliance frameworks including SOC 2, ISO 27001, and NIST.',
    'Security-focused professional with expertise in penetration testing, security architecture review, and risk assessment. Experienced in building security awareness programs, developing incident response playbooks, and collaborating with engineering teams to remediate vulnerabilities.',
    'Cybersecurity analyst skilled in monitoring, analyzing, and responding to security events across cloud and on-premises infrastructure. Experienced in threat modeling, forensic analysis, and implementing zero-trust security architectures.',
  ],
  'network engineer': [
    'Network engineer with [X] years of experience designing, implementing, and maintaining enterprise network infrastructure. CCNP certified with expertise in routing/switching, firewall management, VPN configuration, and network monitoring across multi-site environments.',
    'Experienced network engineer skilled in SD-WAN deployment, cloud networking, and network automation. Proficient in Cisco, Juniper, and Palo Alto platforms with a strong track record of improving network reliability and reducing operational costs.',
  ],
  'systems administrator': [
    'Systems administrator with [X] years of experience managing Linux and Windows server environments in enterprise settings. Skilled in virtualization, Active Directory, automation scripting, and maintaining high-availability infrastructure with 99.9%+ uptime.',
    'Experienced sysadmin skilled in cloud migration, backup and disaster recovery planning, and infrastructure monitoring. Proficient in PowerShell, Bash, and configuration management tools with a focus on security hardening and compliance.',
  ],
  'database administrator': [
    'Database administrator with [X] years of experience managing PostgreSQL, MySQL, and SQL Server databases in high-availability production environments. Skilled in performance tuning, replication, backup strategies, and data modeling for complex analytical workloads.',
    'Experienced DBA with expertise in database migration, capacity planning, and security hardening. Proficient in query optimization, index management, and implementing monitoring solutions that proactively identify and resolve performance bottlenecks.',
  ],
  'teacher': [
    'Dedicated educator with [X] years of experience in [subject/grade level] committed to differentiated instruction and creating inclusive learning environments that foster student growth. Skilled in curriculum development, formative assessment, and integrating technology into daily instruction.',
    'Passionate teacher with expertise in curriculum development and educational technology integration. Strong track record of improving student outcomes through data-driven instruction, collaborative learning strategies, and building positive classroom cultures.',
    'Innovative educator experienced in project-based learning, social-emotional development, and parent engagement. Skilled in adapting instruction to meet diverse learning needs and using assessment data to personalize academic support and intervention plans.',
    'Teacher with [X] years of experience creating engaging, standards-aligned lessons that develop critical thinking and real-world problem-solving skills. Experienced in mentoring student teachers, leading professional development workshops, and contributing to schoolwide improvement initiatives.',
  ],
  'registered nurse': [
    'Compassionate registered nurse with [X] years of experience in [specialty]. Skilled in patient assessment, care planning, and interdisciplinary collaboration in fast-paced clinical settings. Committed to providing holistic, patient-centered care that improves outcomes and patient satisfaction.',
    'Dedicated RN with expertise in acute care and patient education. Committed to evidence-based practice and continuous quality improvement in healthcare delivery with experience in mentoring new nurses and leading unit-level safety initiatives.',
    'Registered nurse with strong clinical skills and a patient-first approach to healthcare. Experienced in emergency care, chronic disease management, and using electronic health records to coordinate care across multidisciplinary teams.',
    'BSN-prepared nurse with [X] years of experience in critical care and telemetry. Skilled in IV therapy, medication administration, wound care, and collaborating with physicians and specialists to develop comprehensive treatment plans for complex patients.',
  ],
  'pharmacist': [
    'Licensed pharmacist with [X] years of experience in retail and clinical pharmacy settings. Skilled in medication therapy management, drug interaction analysis, and patient counseling with a commitment to improving medication adherence and patient outcomes.',
    'Clinical pharmacist experienced in formulary management, antimicrobial stewardship, and interdisciplinary care team collaboration. Proficient in pharmacy information systems and regulatory compliance with a focus on patient safety and quality improvement.',
  ],
  'physician assistant': [
    'Board-certified physician assistant with [X] years of experience providing primary and urgent care to diverse patient populations. Skilled in diagnosis, treatment planning, and patient education with a collaborative approach to healthcare delivery.',
    'Physician assistant with expertise in emergency medicine and procedural skills. Experienced in managing complex cases, performing diagnostic workups, and communicating effectively with patients, families, and healthcare teams in high-acuity settings.',
  ],
  'devops engineer': [
    'DevOps engineer with [X] years of experience automating infrastructure and optimizing CI/CD pipelines across large-scale production environments. Proficient in AWS, Docker, Kubernetes, and infrastructure-as-code tools with a focus on reliability, security, and developer experience.',
    'Cloud-focused DevOps engineer experienced in building resilient, scalable infrastructure that supports hundreds of deployments per week. Passionate about automation, observability, and enabling rapid, reliable software delivery through modern platform engineering practices.',
    'DevOps engineer with expertise in container orchestration, GitOps workflows, and infrastructure monitoring. Experienced in reducing cloud costs, improving deployment reliability, and building internal developer platforms that accelerate product development across engineering teams.',
    'Site reliability-focused DevOps engineer with [X] years of experience managing production systems with 99.99% uptime. Skilled in incident management, capacity planning, chaos engineering, and building self-healing infrastructure that minimizes manual intervention.',
  ],
  'supply chain manager': [
    'Supply chain manager with [X] years of experience optimizing end-to-end supply chain operations from procurement through last-mile delivery. Skilled in demand forecasting, inventory management, and vendor negotiations that consistently reduce costs while maintaining service levels.',
    'Strategic supply chain leader experienced in global logistics, warehouse management, and ERP implementation. Proven track record of building resilient supply chains that navigate disruptions while maintaining customer satisfaction and cost efficiency.',
  ],
  'content strategist': [
    'Content strategist with [X] years of experience developing editorial calendars, brand voice guidelines, and content frameworks that drive organic growth and user engagement. Skilled in SEO, content analytics, and managing cross-functional content production workflows.',
    'Strategic content professional experienced in building content programs from the ground up. Skilled in audience research, competitive analysis, and creating content ecosystems that support marketing, sales, and product adoption goals across multiple channels.',
  ],
  'seo specialist': [
    'SEO specialist with [X] years of experience driving organic traffic growth through technical SEO, content optimization, and link building strategies. Proficient in Google Search Console, SEMrush, and Ahrefs with a track record of achieving top-3 rankings for competitive keywords.',
    'Data-driven SEO professional skilled in technical site audits, keyword research, and content strategy development. Experienced in collaborating with engineering and content teams to implement improvements that increase organic visibility and conversion rates.',
  ],
  'program manager': [
    'Program manager with [X] years of experience orchestrating complex, multi-team initiatives across engineering, product, and business operations. Skilled in defining program roadmaps, managing dependencies, and ensuring alignment between strategic goals and execution.',
    'Strategic program manager experienced in driving cross-functional programs from planning through delivery. Expert in stakeholder communication, risk management, and building program governance structures that enable teams to deliver ambitious goals on schedule.',
  ],
}

// ── Common Degrees ──────────────────────────────────────────────────────────

export const COMMON_DEGREES: string[] = [
  'B.S. Computer Science',
  'B.S. Electrical Engineering',
  'B.S. Mechanical Engineering',
  'B.S. Information Technology',
  'B.S. Mathematics',
  'B.S. Biology',
  'B.S. Chemistry',
  'B.S. Physics',
  'B.S. Business Administration',
  'B.S. Nursing',
  'B.A. English',
  'B.A. Psychology',
  'B.A. Communications',
  'B.A. Political Science',
  'B.A. Economics',
  'B.A. History',
  'B.A. Sociology',
  'B.A. Graphic Design',
  'B.A. Marketing',
  'M.S. Computer Science',
  'M.S. Data Science',
  'M.S. Electrical Engineering',
  'M.S. Mechanical Engineering',
  'M.S. Information Systems',
  'M.A. Education',
  'M.A. English',
  'M.A. Psychology',
  'MBA',
  'Ph.D. Computer Science',
  'Ph.D. Physics',
  'Ph.D. Chemistry',
  'Ph.D. Biology',
  'J.D.',
  'M.D.',
  'Associate of Science',
  'Associate of Arts',
]

// ── Common Schools ──────────────────────────────────────────────────────────

export const COMMON_SCHOOLS: string[] = [
  'Massachusetts Institute of Technology',
  'Stanford University',
  'Harvard University',
  'California Institute of Technology',
  'University of Chicago',
  'Princeton University',
  'Columbia University',
  'Yale University',
  'University of Pennsylvania',
  'Duke University',
  'Northwestern University',
  'Johns Hopkins University',
  'Cornell University',
  'Rice University',
  'Vanderbilt University',
  'University of Notre Dame',
  'Washington University in St. Louis',
  'Georgetown University',
  'Carnegie Mellon University',
  'University of Michigan',
  'University of Virginia',
  'Georgia Institute of Technology',
  'University of California, Berkeley',
  'University of California, Los Angeles',
  'University of California, San Diego',
  'University of Southern California',
  'New York University',
  'Boston University',
  'University of Texas at Austin',
  'University of Washington',
  'University of Wisconsin-Madison',
  'University of Illinois Urbana-Champaign',
  'Purdue University',
  'University of Florida',
  'Penn State University',
  'Ohio State University',
  'University of Minnesota',
  'University of Maryland',
  'Texas A&M University',
  'Arizona State University',
  'University of Colorado Boulder',
  'University of North Carolina at Chapel Hill',
  'Virginia Tech',
  'Michigan State University',
  'Indiana University',
  'University of Arizona',
  'University of Oregon',
  'Rutgers University',
  'University of Iowa',
  'University of Pittsburgh',
  // ── Additional state universities ──
  'University of Alabama',
  'University of Arkansas',
  'University of Connecticut',
  'University of Delaware',
  'University of Georgia',
  'University of Hawaii at Manoa',
  'University of Idaho',
  'University of Kansas',
  'University of Kentucky',
  'University of Louisville',
  'University of Maine',
  'University of Massachusetts Amherst',
  'University of Mississippi',
  'University of Missouri',
  'University of Montana',
  'University of Nebraska-Lincoln',
  'University of Nevada, Las Vegas',
  'University of Nevada, Reno',
  'University of New Hampshire',
  'University of New Mexico',
  'University of North Dakota',
  'University of Oklahoma',
  'University of Rhode Island',
  'University of South Carolina',
  'University of South Dakota',
  'University of South Florida',
  'University of Tennessee',
  'University of Utah',
  'University of Vermont',
  'University of Wyoming',
  'Auburn University',
  'Baylor University',
  'Brigham Young University',
  'Clemson University',
  'Colorado State University',
  'Florida State University',
  'Iowa State University',
  'Kansas State University',
  'Louisiana State University',
  'Mississippi State University',
  'North Carolina State University',
  'Oklahoma State University',
  'Oregon State University',
  'San Diego State University',
  'San Jose State University',
  'University of Central Florida',
  'University of Cincinnati',
  'University of Houston',
  'University of Memphis',
  'University of North Texas',
  'University of Texas at Dallas',
  'University of Texas at San Antonio',
  'University of Toledo',
  'University of Tulsa',
  'Utah State University',
  'Washington State University',
  'West Virginia University',
  'Western Michigan University',
  'Wichita State University',
  // ── HBCUs ──
  'Howard University',
  'Morehouse College',
  'Spelman College',
  'Hampton University',
  'Tuskegee University',
  'Florida A&M University',
  'North Carolina A&T State University',
  'Tennessee State University',
  'Xavier University of Louisiana',
  'Clark Atlanta University',
  'Morgan State University',
  'Prairie View A&M University',
  'Southern University',
  'Jackson State University',
  'Grambling State University',
  // ── Community colleges ──
  'Miami Dade College',
  'Houston Community College',
  'Northern Virginia Community College',
  'Austin Community College',
  'Portland Community College',
  'Lone Star College',
  'Salt Lake Community College',
  'Tarrant County College',
  'Sinclair Community College',
  'Community College of Denver',
  'Santa Monica College',
  'De Anza College',
  'Montgomery College',
  'Maricopa Community Colleges',
  'Ivy Tech Community College',
  // ── Private universities ──
  'Boston College',
  'Brandeis University',
  'Brown University',
  'Case Western Reserve University',
  'Dartmouth College',
  'Drexel University',
  'Emory University',
  'Fordham University',
  'George Washington University',
  'Gonzaga University',
  'Lehigh University',
  'Loyola University Chicago',
  'Marquette University',
  'Northeastern University',
  'Pepperdine University',
  'Santa Clara University',
  'Southern Methodist University',
  'Syracuse University',
  'Tufts University',
  'Tulane University',
  'University of Denver',
  'University of Miami',
  'University of Rochester',
  'University of San Francisco',
  'Villanova University',
  'Wake Forest University',
  // ── International universities ──
  'University of Toronto',
  'University of British Columbia',
  'McGill University',
  'University of Waterloo',
  'University of Oxford',
  'University of Cambridge',
  'Imperial College London',
  'London School of Economics',
  'University College London',
  'ETH Zurich',
  'Technical University of Munich',
  'University of Tokyo',
  'National University of Singapore',
  'University of Melbourne',
  'University of Sydney',
  'Tsinghua University',
  'Peking University',
  'Seoul National University',
  'KAIST',
  'Indian Institute of Technology (IIT)',
]

// ── Tech Suggestions from Skills ────────────────────────────────────────────

const RELATED_TECH: Record<string, string[]> = {
  react: ['Next.js', 'Redux', 'React Router', 'Zustand', 'TanStack Query'],
  'next.js': ['Vercel', 'React', 'TypeScript', 'Tailwind CSS', 'Prisma'],
  typescript: ['JavaScript', 'Node.js', 'ESLint', 'Zod'],
  python: ['Django', 'Flask', 'FastAPI', 'Pandas', 'NumPy'],
  'node.js': ['Express', 'NestJS', 'TypeScript', 'MongoDB', 'PostgreSQL'],
  java: ['Spring Boot', 'Maven', 'Gradle', 'JUnit', 'Hibernate'],
  docker: ['Kubernetes', 'Docker Compose', 'CI/CD', 'AWS ECS'],
  aws: ['S3', 'EC2', 'Lambda', 'CloudFormation', 'DynamoDB'],
  postgresql: ['SQL', 'Prisma', 'Sequelize', 'pgAdmin'],
  mongodb: ['Mongoose', 'MongoDB Atlas', 'NoSQL'],
  vue: ['Nuxt.js', 'Vuex', 'Pinia', 'Vue Router'],
  angular: ['RxJS', 'NgRx', 'TypeScript', 'Jasmine'],
  flutter: ['Dart', 'Firebase', 'iOS', 'Android'],
  swift: ['SwiftUI', 'UIKit', 'Xcode', 'iOS', 'Core Data'],
  kotlin: ['Android', 'Jetpack Compose', 'Ktor', 'Gradle'],
  go: ['Gin', 'gRPC', 'Docker', 'Kubernetes'],
  rust: ['Cargo', 'Tokio', 'WebAssembly', 'Actix'],
  'c#': ['.NET', 'ASP.NET', 'Entity Framework', 'Azure', 'Unity'],
  sql: ['PostgreSQL', 'MySQL', 'SQLite', 'Data Modeling'],
  tailwind: ['CSS', 'PostCSS', 'Responsive Design', 'shadcn/ui'],
  figma: ['Adobe XD', 'Sketch', 'Design Systems', 'Prototyping'],
  git: ['GitHub', 'GitLab', 'CI/CD', 'Code Review'],
}

export function getTechSuggestionsFromSkills(skills: string[]): string[] {
  const existing = new Set(skills.map((s) => s.toLowerCase()))
  const suggestions = new Set<string>()

  for (const skill of skills) {
    const related = RELATED_TECH[skill.toLowerCase()]
    if (related) {
      for (const tech of related) {
        if (!existing.has(tech.toLowerCase())) {
          suggestions.add(tech)
        }
      }
    }
  }

  return Array.from(suggestions)
}

// ── Year Estimation ──────────────────────────────────────────────────────────

import type { Experience } from '@/types/resume'

const MONTH_MAP: Record<string, number> = {
  jan: 0, january: 0, feb: 1, february: 1, mar: 2, march: 2,
  apr: 3, april: 3, may: 4, jun: 5, june: 5,
  jul: 6, july: 6, aug: 7, august: 7, sep: 8, september: 8,
  oct: 9, october: 9, nov: 10, november: 10, dec: 11, december: 11,
}

function parseDateToMs(dateStr: string): number | null {
  if (!dateStr) return null
  const lower = dateStr.toLowerCase().trim()
  if (lower === 'present' || lower === 'current') return Date.now()
  // Try "Mon YYYY" or "Month YYYY"
  const parts = lower.split(/[\s,/]+/)
  for (const part of parts) {
    if (MONTH_MAP[part] !== undefined) {
      const yearPart = parts.find((p) => /^\d{4}$/.test(p))
      if (yearPart) return new Date(parseInt(yearPart), MONTH_MAP[part]).getTime()
    }
  }
  // Try just year
  const yearMatch = lower.match(/\d{4}/)
  if (yearMatch) return new Date(parseInt(yearMatch[0]), 0).getTime()
  return null
}

export function estimateYearsOfExperience(experience: Experience[]): string {
  let totalMs = 0
  for (const exp of experience) {
    const start = parseDateToMs(exp.startDate)
    const end = parseDateToMs(exp.endDate)
    if (start && end && end > start) {
      totalMs += end - start
    }
  }
  const years = Math.round(totalMs / (365.25 * 24 * 60 * 60 * 1000))
  if (years <= 0) return '1'
  return `${years}+`
}

// ── Lookup Functions with Fuzzy Matching ─────────────────────────────────────

function fuzzyLookup<T>(
  title: string,
  data: Record<string, T>,
  fallback: T
): T {
  if (!title) return fallback
  const lower = title.toLowerCase()

  // Exact match
  if (data[lower]) return data[lower]

  // Partial match — check if any key is included in the title or vice versa
  for (const key of Object.keys(data)) {
    if (lower.includes(key) || key.includes(lower)) {
      return data[key]
    }
  }

  return fallback
}

export function getSkillsForJob(title: string): string[] {
  return fuzzyLookup(title, SKILLS_BY_JOB, [])
}

export function getDescriptionBullets(title: string): string[] {
  return fuzzyLookup(title, DESCRIPTION_BULLETS_BY_JOB, [])
}

export function getSummaryTemplates(title: string): string[] {
  const specific = fuzzyLookup(title, SUMMARY_TEMPLATES_BY_JOB, [])
  if (specific.length > 0) return [...specific, ...GENERIC_SUMMARY_TEMPLATES]
  return GENERIC_SUMMARY_TEMPLATES
}
